Settings:
  Enabled: true
  Secret-Code: "-ZWO2VPY6UTLBU9ISFRHK-"

Whitelist:
  Farming: # Must be the material of the placed drop - not the crop given when harvested (e.g. CARROTS instead of CARROT)
    - "WHEAT"
    - "CARROTS"
    - "POTATOES"
  Fishing:
    - "SALMON"
    - "COD"
    - "TROPICAL_FISH"
    - "PUFFERFISH"
  Mining:
    - "COAL_ORE"
    - "IRON_ORE"
    - "GOLD_ORE"
    - "DIAMOND_ORE"
  Mobs:
    - "ZOMBIE"
    - "CREEPER"
    - "WITCH"
    - "SKELETON"

Allowed-Worlds:
  Farming:
    - "build"
  Fishing:
    - "lake"
  Mining:
    - "Mine"
  Mobs:
    - "Mob"

Trophy:
  Fish:
    Value: !long 1000
  Mob:
    Value: !long 750
  Ore:
    Value: !long 500
  Crop:
    Value: !long 250

Strikes:
  Strike-One: !long 10
  Strike-Two: !long 35
  Strike-Three: !long 70
  Strike-Four: !long 100


Formats:
  CropTop: "&2&l#%position% &a%player% &2- &a%value%"
  FishTop: "&3&l#%position% &b%player% &3- &b%value%"
  MobTop: "&4&l#%position% &c%player% &4- &c%value%"
  OreTop: "&5&l#%position% &d%player% &5- &d%value%"